# GitHub Actions Workflow for Cross-Platform R Testing

name: R-CMD-check

# Trigger on push or pull request to main/master branches
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

# Grant write permissions for contents
permissions:
  contents: write

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (R-${{ matrix.config.r }})

    # Test on multiple OS platforms
    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: ubuntu-latest, r: "release" }
          - { os: windows-latest, r: "release" }
          - { os: macOS-latest, r: "release" }

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          use-public-rspm: true

      # Linux only
      - name: Install system dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

      - name: Install R dependencies
        run: |
          install.packages(c("testthat", "ggplot2", "dplyr", "tidyr", "knitr"))
          install.packages(c("remotes", "rcmdcheck", "xml2"))
        shell: Rscript {0}

      # Optional packages - allowed to fail
      - name: Install optional packages
        continue-on-error: true
        run: |
          if (!requireNamespace("BiocManager", quietly = TRUE)) {
            install.packages("BiocManager")
          }
          BiocManager::install("mixOmics", ask = FALSE)
          install.packages("rARPACK")
          install.packages("RSpectra")
          install.packages("bench")
        shell: Rscript {0}

      - name: Session info
        run: |
          options(width = 100)
          pkgs <- installed.packages()[, "Package"]
          sessioninfo::session_info(pkgs, include_base = TRUE)
        shell: Rscript {0}

      - name: Run tests
        run: |
          library(testthat)

          # Load all R function files from R/ directory
          cat("\n=== Loading R functions ===\n")
          r_files <- list.files("R", pattern = "\\.R$", full.names = TRUE)
          for (f in r_files) {
            cat("Loading:", f, "\n")
            source(f)
          }

          # Show all failures
          set_max_fails(Inf)

          # Create test-results directory if it doesn't exist
          # Use absolute path because test_file() changes working directory
          project_root <- getwd()
          test_results_dir <- file.path(project_root, "test/testthat/test-results")
          if (!dir.exists(test_results_dir)) {
            dir.create(test_results_dir, recursive = TRUE)
          }

          # Define output file with OS and R version info
          os_name <- "${{ matrix.config.os }}"
          r_version <- "${{ matrix.config.r }}"
          output_file <- file.path(test_results_dir, paste0("test-results-", os_name, "-", r_version, ".xml"))

          # Run test-pca_pSVD.R only
          cat("\n=== Running test-pca_pSVD.R ===\n")

          # Define summary output file
          summary_file <- file.path(test_results_dir, paste0("summary-", os_name, "-", r_version, ".txt"))

          test_results <- test_file(
            "test/testthat/test-pca_pSVD.R",
            reporter = MultiReporter$new(reporters = list(
              ProgressReporter$new(),
              FailReporter$new(),
              SummaryReporter$new(file = summary_file)
            )),
            stop_on_failure = FALSE
          )

          # Display summary
          cat("\n=== Test Summary ===\n")
          print(test_results)

          # Verify test-results.xml was created
          cat("\n=== Checking test results file ===\n")
          cat("Expected output file:", output_file, "\n")
          cat("Working directory:", getwd(), "\n")
          cat("test-results directory exists:", dir.exists(test_results_dir), "\n")

          if (dir.exists(test_results_dir)) {
            cat("Files in test/testthat/test-results/:\n")
            print(list.files(test_results_dir, full.names = TRUE))
          }

          if (file.exists(output_file)) {
            cat("\n✓", output_file, "created successfully\n")
            cat("File size:", file.size(output_file), "bytes\n")
          } else {
            cat("\n✗ WARNING:", output_file, "was not created\n")
            cat("This may indicate JunitReporter failed to write the file\n")
          }

          # Exit with error if tests failed
          if (any(as.data.frame(test_results)$failed > 0)) {
            cat("\n✗ Tests FAILED\n")
            quit(status = 1)
          } else {
            cat("\n✓ All tests PASSED\n")
          }
        shell: Rscript {0}

      - name: Check test-results directory
        if: always()
        run: |
          echo "=== Debugging: Checking test-results directory ==="
          pwd
          ls -la
          if [ -d "test/testthat/test-results" ]; then
            echo "test/testthat/test-results directory exists"
            ls -la test/testthat/test-results/
          else
            echo "test/testthat/test-results directory does NOT exist"
          fi
        shell: bash

      - name: Commit test results
        if: always()
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Add test results for ${{ matrix.config.os }} (R-${{ matrix.config.r }})"
          file_pattern: "test/testthat/test-results/*.txt"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
          skip_dirty_check: false
          pull: "--rebase --autostash"

      # Run benchmark
      # - name: Run benchmark
      #   if: runner.os == 'Linux'
      #   continue-on-error: true
      #   run: |
      #     if (file.exists("pca_pSVD.Rmd")) {
      #       rmarkdown::render("pca_pSVD.Rmd")
      #     }
      #   shell: Rscript {0}
